export const UI = {
    button: {
        radius: 10,
        pressedOpacity: 0.85,
        disabledOpacity: 0.5,
        minHeightSm: 36,
        minHeightMd: 44,
        minHeightLg: 48,
    },
    auth: {
        titleFontSize: 32,
        inputRadius: 10,
        inputMinHeight: 48,
        formGap: 16,
        buttonPressedOpacity: 0.8,
        linkPressedOpacity: 0.6,
        devDividerWidth: 1,
    },
    filter: {
        chipGap: 6,
        chipMinHeight: 30,
        labelFontSize: 13,
        clearIconSize: 16,
        checkIconSize: 14,
        containerShadowOpacity: 0.1,
        containerShadowRadius: 4,
        containerShadowOffset: { width: 0, height: 2 },
        containerElevation: 3,
    },
    tabs: {
        headerTitleSize: 28,
        tabBarHeight: 72,
        reviewIconSize: 26,
        reviewButtonSize: 60,
        reviewButtonRadius: 30,
        reviewButtonBorderWidth: 3,
        reviewButtonMarginTop: -20,
        reviewButtonElevation: 4,
    },
    homeSheet: {
        minExpandedHeight: 360,
        collapsedHeight: 92,
        topGap: 8,
        horizontalInset: 10,
        shadowOpacity: 0.16,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: -4 },
        elevation: 10,
        handleBarWidth: 42,
        handleBarHeight: 4,
        handleBarRadius: 99,
        handleGestureMinHeight: 44,
    },
    placeholder: {
        mapIconSize: 64,
    },
    feedback: {
        pressedSoftOpacity: 0.7,
    },
    review: {
        cardRadius: 28,
        cardBorderWidth: 2,
        cardShadowOpacity: 0.25,
        cardShadowRadius: 16,
        cardShadowOffset: { width: 0, height: 8 },
        cardElevation: 8,
        titleFontSize: 30,
        labelLetterSpacing: 1,
    },
    slider: {
        shellHeight: 74,
        knobSize: 58,
        trackHeight: 14,
        tickSize: 8,
        borderRound: 999,
        beanInnerInset: 8,
        beanCreaseWidth: 8,
        beanShineWidth: 14,
        beanShineHeight: 8,
    },
    map: {
        recenterButtonSize: 42,
        recenterButtonRadius: 21,
        recenterButtonIconSize: 18,
        recenterButtonZIndex: 25,
        recenterButtonElevation: 6,
    },
} as const;
